# Generated by Django 5.2 on 2025-06-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_cliente_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
